# Copyright 2022 Centro ALGORITMI - University of Minho
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mepserver.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mepserver.name }}
spec:
  replicas: {{ .Values.mepserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mepserver.name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.mepserver.name }}
    spec:
      containers:
      - name: {{ .Values.mepserver.name }}
        image: "{{ .Values.mepserver.image }}"
        ports:
        - containerPort: {{ .Values.mepserver.service.targetPort }}
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
          - name: ME_CONFIG_MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_port
          - name: ME_CONFIG_MONGODB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_name                
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb_username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb_password
          - name: OAUTH_SERVER
            valueFrom:
              configMapKeyRef:
                name: auth-configmap
                key: auth-server-url
          - name: OAUTH_PORT
            valueFrom:
              configMapKeyRef:
                name: auth-configmap
                key: auth-server-port
          - name: DNS_API_SERVER
            valueFrom:
              configMapKeyRef:
                name: dnsapi-configmap
                key: dnsapi-server-url
          - name: DNS_API_PORT
            valueFrom:
              configMapKeyRef:
                name: dnsapi-configmap
                key: dnsapi-server-port                
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mepserver.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mepserver.name }}
spec:
  selector:
    app: {{ .Values.mepserver.name }}
  ports:
  - name: {{ .Values.mepserver.name }}
    protocol: TCP
    port: {{ .Values.mepserver.service.port }}
    targetPort: {{ .Values.mepserver.service.targetPort }}
    nodePort: {{ .Values.mepserver.service.nodePort }}
  type: {{ .Values.mepserver.service.type }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mepserver.name }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.mepserver.name }}-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch","update","create", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get","list","watch","update","create","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.mepserver.name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.mepserver.name }}-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}