# Copyright 2022 Centro ALGORITMI - University of Minho
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongoexpress.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.mongoexpress.name }}
    app.kubernetes.io/instance: {{ .Values.appInstanceId }}
spec:
  replicas: {{ .Values.mongoexpress.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.mongoexpress.name }}
      app.kubernetes.io/instance: {{ .Values.appInstanceId }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app.kubernetes.io/name: {{ .Values.mongoexpress.name }}
        app.kubernetes.io/instance: {{ .Values.appInstanceId }}
    spec:
      containers:
      - name: {{ .Values.mongoexpress.name }}
        image: "{{ .Values.mongoexpress.image }}"
        ports:
        - containerPort: {{ .Values.mongoexpress.service.targetPort }}
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
          - name: ME_CONFIG_MONGODB_PORT
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_port
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb_username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb_password
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoexpress.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.mongoexpress.name }}
    app.kubernetes.io/instance: {{ .Values.appInstanceId }}
    
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.mongoexpress.name }}
    app.kubernetes.io/instance: {{ .Values.appInstanceId }}
  ports:
  - protocol: TCP
    port: {{ .Values.mongoexpress.service.port }}
    targetPort: {{ .Values.mongoexpress.service.targetPort }}
    nodePort: {{ .Values.mongoexpress.service.nodePort }}
  type: {{ .Values.mongoexpress.service.type }}