version: "3.8"

services:
  mepserver:
    image: vinicf/netedge-mepserver
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"    

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
